name: HolographicDisplays
main: com.gmail.filoghost.holograms.HolographicDisplays
version: 1.5

softdepend: [Multiverse-Core, MultiWorld]

commands:
   holograms:
      description: Main command for HolographicDisplays.
      usage: /<command> (Startup error)
      aliases: [hd, holo, hologram]