name: HolographicDisplays
main: com.gmail.filoghost.holograms.HolographicDisplays
version: 1.6

softdepend: [Multiverse-Core, MultiWorld, My Worlds, My_Worlds]

commands:
   holograms:
      description: Main command for HolographicDisplays.
      usage: /<command> (Startup error)
      aliases: [hd, holo, hologram]